services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=magic_cinema_db'
      - 'POSTGRES_PASSWORD=Dylan123'
      - 'POSTGRES_USER=zairex-code'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: