
server.port=7777
spring.application.name=magic-cinema
server.servlet.context-path=/magic-cinema/api

# THIS IS A TEMPORAL API KEY THAT I CREATE
# 1. API KEY
langchain4j.open-ai.chat-model.api-key=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
# 2. ROUTE
langchain4j.open-ai.chat-model.base-url=https://openrouter.ai/api/v1
# 3. Model
langchain4j.open-ai.chat-model.model-name=openrouter/free
# get logs from requests and responses 
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

# Spring Data JPA

Spring.datasource.url= jdbc:postgresql://localhost:5432/magic_cinama_db
Spring.datasource.username= zairex-code
Spring.datasource.password = Dylan123

# theay are planes if detec somme changes modify the db its like migrations in laravel
spring.jpa.hibernate.ddl-auto=update
#show in the console what is hapenning
spring.jpa.show-sql = true
#format sql if its necesary to make it easy to read
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always





# Activa el nivel DEBUG para LangChain4j.
# Permite ver información detallada sobre el flujo interno de LangChain4j,
# incluyendo llamadas, configuración y procesos relacionados con el modelo de IA.
logging.level.dev.langchain4j=DEBUG

# Activa el nivel DEBUG para la librería OpenAI4j usada por LangChain4j.
# Permite inspeccionar detalles de comunicación con el proveedor OpenAI/OpenRouter,
# como construcción de peticiones, respuestas y posibles errores de integración.
logging.level.dev.ai4j.openai4j=DEBUG