spring.application.name=magic-cinema
# 1. Tu llave real de OpenRouter (empieza con sk-or-v1-...)
langchain4j.open-ai.chat-model.api-key=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

# La ruta hacia OpenRouter
langchain4j.open-ai.chat-model.base-url=https://openrouter.ai/api/v1

# El comodín universal: OpenRouter elegirá automáticamente el mejor modelo gratuito que esté en línea en ese segundo
langchain4j.open-ai.chat-model.model-name=openrouter/free