spring.profiles.active=dev

spring.application.name=magic-cinema
server.servlet.context-path=/magic-cinema/api


# El comodín universal: OpenRouter elegirá automáticamente el mejor modelo gratuito que esté en línea en ese segundo
langchain4j.open-ai.chat-model.model-name=openrouter/free

#PostgreSQL
Spring.datasource.driver-class-name=org.postgresql.Driver

