INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('The Matrix', 136, 'CIENCIA_FICCION', 4.80, '1999-03-31', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Gladiador', 155, 'ACCION', 4.70, '2000-05-05', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('El Padrino', 175, 'DRAMA', 4.90, '1972-03-24', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Spider-Man: Into the Spider-Verse', 117, 'ANIMADA', NULL, '2018-12-14', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Mad Max: Fury Road', 120, 'ACCION', 4.60, '2015-05-15', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Parasite', 132, 'DRAMA', 4.80, '2019-05-30', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Alien', 117, 'TERROR', NULL, '1979-05-25', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Jurassic Park', 127, 'CIENCIA_FICCION', 4.50, '1993-06-11', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('The Dark Knight', 152, 'ACCION', 4.90, '2008-07-18', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Forrest Gump', 142, 'DRAMA', 4.80, '1994-07-06', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Shrek 2', 92, 'ANIMADA', NULL, '2004-05-19', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('El Resplandor', 146, 'TERROR', 4.70, '1980-05-23', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Volver al Futuro', 116, 'CIENCIA_FICCION', 4.80, '1985-07-03', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Terminator 2: Judgment Day', 137, 'ACCION', NULL, '1991-07-03', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('El Viaje de Chihiro', 125, 'ANIMADA', 4.90, '2001-07-20', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Psicosis', 109, 'TERROR', 4.60, '1960-09-08', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Blade Runner 2049', 164, 'CIENCIA_FICCION', NULL, '2017-10-06', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Fight Club', 139, 'DRAMA', 4.80, '1999-10-15', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Supercool', 113, 'COMEDIA', 4.30, '2007-08-17', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Up', 96, 'ANIMADA', 4.70, '2009-05-29', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Hereditary', 127, 'TERROR', NULL, '2018-06-08', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Die Hard', 132, 'ACCION', 4.60, '1988-07-15', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Avatar', 162, 'CIENCIA_FICCION', 4.40, '2009-12-18', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('La La Land', 128, 'DRAMA', NULL, '2016-12-09', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('WALL-E', 98, 'ANIMADA', 4.80, '2008-06-27', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Un Lugar en Silencio', 90, 'TERROR', 4.40, '2018-04-06', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Kill Bill: Vol. 1', 111, 'ACCION', NULL, '2003-10-10', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('E.T. el Extraterrestre', 115, 'CIENCIA_FICCION', 4.60, '1982-06-11', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('El Rey León', 89, 'ANIMADA', 4.80, '1994-06-15', 'A') ON CONFLICT (title) DO NOTHING;
INSERT INTO magic_cinema_movies (title, duration, genre, clasification, release_date, status) VALUES ('Duna: Parte Uno', 155, 'CIENCIA_FICCION', 4.70, '2021-10-22', 'A') ON CONFLICT (title) DO NOTHING;